.TH man 1 "30 Jan, 2017" "1.0" "amcrest-tui man page"
.SH NAME
amcrest-cli \- A text user interface for amcrest camera
.SH SYNOPSIS
amcrest-tui
.SH DESCRIPTION
\fBamcrest-tui\fP is python3 only text user interface to visualize snapshots from Amcrest cameras.
.br
By default it reads the default ~/.config/amcrest.conf configuration file.
.SH NOTES:
NOTE0:
Execute it from console logins, \fBlike /dev/ttyX (Non X Windows)\fP. Pseudo-terminals like xterm, ssh, screen and others \fB*WON'T WORK*\fP.
.br
NOTE1: As it uses framebuffer to visualize the snapshots, make sure your user has permission to manage /dev/fb0.
.br
NOTE2: If you use sudo command, make sure you put the amcrest.conf in /root/.config/amcrest.conf
.P
.SH amcrest.conf format:
.br
The current format for ~/.config/amcrest.conf is:
.PP
.RS
[mycamera1]
.br
hostname: mycamera1.example.com
.br
username: admin
.br
password: 1234567
.br
port: 80
.P
[mycamera2]
.br
hostname: mycamera2.example.com
.br
username: admin
.br
password: 7654321
.br
port: 80
.RE
.P
.SH OPTIONS
.TP
.B -h, --help
Displays a list of options.
.TP
.B --config-file-name CONFIG_FILE_NAME [optional]
specify the amcrest config file, default ~/.config/amcrest.conf
.TP
.B --channel-snapshot CHANNEL_SNAPSHOT [optional]
channel used for the snapshot, default is 0
.TP
.B --framebuffer-device FRAMEBUFFER_DEVICE [optional]
speficy the framebuffer device, default /dev/fb0
.TP
.B --timer-between-snapshots TIMER_BETWEEN_SNAPSHOTS [optional]
timer between snapshots, default 2 sec
.TP
.B --timeout-error-msg TIMEOUT_ERROR_MSG [optional]
timeout in case errors messages should be displayed, default 5sec
.TP
.B --merge-snapshots MERGE_SNAPSHOTS [optinal]
merge snapshots from all cameras in one photo to be displayed
.TP
.SH BUGS
Report bugs to <https://github.com/tchellomello/python-amcrest/issues>
.SH "SEE ALSO"
.BR amcrest-tui (1)
.SH COPYRIGHT
Copyright 2016-2017
License GPLv2: GNU GPL Version 2 <http://gnu.org/licenses/gpl.html>.
