.TH man 1 "23 Oct, 2016" "1.0" "amcrest-cli man page"
.SH NAME
amcrest-cli \- A tool to manage Amcrest camera
.SH SYNOPSIS
amcrest-cli -H HOSTNAME -u USERNAME -p PASSWORD [options]
.SH DESCRIPTION
\fBamcrest-cli\fP is a command line tool to manage Amcrest camera
.SH OPTIONS
.TP
.B -h, --help
Displays a list of options.
.TP
.B --current-time
Get current time from camera.
.TP
.B --snapshot
Get snapshot, use one of the following options:
.br
0 - regular snapshot
.br
1 - motion detection snapshot
.br
2 - alarm snapshot
.TP
.B --output
output file name, useful for options like --snapshot, --config-backup
.TP
.B --motion-detection-status
Returns if the motion detection is enabled or disabled
.TP
.B --motion-detection
Enable or Disable motion detection, use true or false
.TP
.B --general-config
Get general config
.TP
.B --network-config
Get network config
.TP
.B --telnet-config
Show or set telnet service, use true or false
.TP
.B --version-http-api
Get version of HTTP API
.TP
.B --network-interfaces
Get network interfaces
.TP
.B --vendor-information
Get vendor information
.TP
.B --onvif-information
Get Onvif information
.TP
.B --software-information
Get software information
.TP
.B --system-information
Get system information
.TP
.B --serial-number
Get serial number
.TP
.B --machine-name
Get machine name
.TP
.B --device-class
Get device class
.TP
.B --device-type
Get device type
.TP
.B --config-backup
Download all settings of a device
.TP
.B --hardware-version
Get hardware version
.TP
.B --scan-devices
.br
Scan amcrest cameras in the subnet provided. Masks support: /16, /24, /25, /27, /28, /29, /30, /31
.br
If mask not provide, will be used /24.
.TP
.B --info-user <username>
Get information about the username
.TP
.B --info-all-users
Get information about all usernames
.TP
.B --info-all-active-users
Get information about all active users
.TP
.B --info-group <group>
Get information about group
.TP
.B --info-all-groups
Get information about all groups
.TP
.B --delete-user <username>
Delete user
.TP
.B --video-blind-detect-config
Get video blind detect config
.TP
.B --video-loss-detect-config
Get video loss detect config
.TP
.B --event-handler-config <configname>
Get event handler configname
.TP
.B --alarm-config
get alarm config
.TP
.B --alarm-out-config
get alarm out config
.TP
.B --alarm-states-output-channels
alarm states output channels
.TP
.B --alarm-states-input-channels
alarm states input channels
.TP
.B --alarm-input-channels
alarm input channels
.TP
.B --alarm-output-channels
alarm output channels
.TP
.B --event-login-failure
event login failure
.TP
.B --event-storage-not-exist
event storage not exist
.TP
.B --event-management
event management
.TP
.B --event-storage-access-failure
event storage access failure
.TP
.B --event-storage-low-space
event storage low space
.TP
.B --event-net-abort
event net abort
.TP
.B --event-ip-conflict
event ip conflict
.TP
.B --event-channels-happened <channel>
channel params: VideoMotion, VideoLoss, VideoBlind, Alarmlocal
.TP
.B --audio-input-channels-numbers
audio input channels numbers
.TP
.B --audio-output-channels-numbers
audio output channels numbers
.TP
.B --record-capability
show record capability
.TP
.B --record-config
show record config
.TP
.B --media-global-config
media global config
.TP
.B --video-max-extra-stream
max extra stream
.TP
.B --video-color-config
color config
.TP
.B --encode-capability
encode capability
.TP
.B --encode-config-capability
encode config capability
.TP
.B --encode-media
encode media
.TP
.B --encode-region-interested
encode region interested
.TP
.B --video-channel-title
channel title
.TP
.B --video-input-channels-device-supported
input channels device supported
.TP
.B --video-output-channels-device-supported
output channels device supported
.TP
.B --video-max-remote-input-channels
max remote input channels
.TP
.B --video-in-options
video in options
.TP
.B --video-out-options
video out options
.TP
.B --video-input-capability
video input capability
.TP
.B --video-coordinates-current-window <channel>
set coordinates current window
.TP
.B --video-standard [PAL or NTSC]
view/set video standard <PAL or NTSC>
.SH EXAMPLES
.TP
.B Get general config
$ amcrest-cli -H 192.168.1.10 -u admin -p password --general-config
.TP
.B Grab snapshot and save in /tmp/self.jpeg
$ amcrest-cli -H 192.168.1.10 -u admin -p password --snapshot --output /tmp/self.jpeg
.TP
.B Check if motion detection is enable or disable
$ amcrest-cli -H 192.168.1.10 -u admin -p password --motion-detection
.TP
.B Enable motion detection
$ amcrest-cli -H 192.168.1.10 -u admin -p password --motion-detection true
.TP
.B Disable motion detection
$ amcrest-cli -H 192.168.1.10 -u admin -p password --motion-detection false
.TP
.B Get network config
$ amcrest-cli -H 192.168.1.10 -u admin -p password --network-config
.TP
.B Get network interfaces
$ amcrest-cli -H 192.168.1.10 -u admin -p password --network-interfaces
.TP
.B Get current time
$ amcrest-cli -H 192.168.1.10 -u admin -p password --current-time
.TP
.B Set current time
$ amcrest-cli -H 192.168.1.10 -u admin -p password --current-time "2016-10-28 13-48-00"
.TP
.B Scan Amcrest devices
$ amcrest-cli -H 192.168.1.10 --scan-devices 192.168.0.1/24
.TP
.B Get version of HTTP API
$ amcrest-cli -H 192.168.1.10 -u admin -p password --version-http-api
.TP
.B Get device type
$ amcrest-cli -H 192.168.1.10 -u admin -p password --device-type
.TP
.B Show telnet service settings
$ amcrest-cli -H 192.168.1.10 -u admin -p password --telnet-config
.TP
.B Disable telnet service
$ amcrest-cli -H 192.168.1.10 -u admin -p password --telnet-config false
.TP
.B Get software information
$ amcrest-cli -H 192.168.1.10 -u admin -p password --software-information
.SH BUGS
Report bugs to <https://github.com/tchellomello/python-amcrest/issues>
.SH COPYRIGHT
Copyright 2016
License GPLv2: GNU GPL Version 2 <http://gnu.org/licenses/gpl.html>.
