name: Publish to PyPI
on:
  push:
    branches-ignore: ['*']
    tags: ['*']
  release:
    types: [published]
jobs:
  build-source:
    name: Push source build
    runs-on: ubuntu-latest
    env:
      python-version: "3.10"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools wheel
      - name: Build source
        run: |
          python setup.py bdist_wheel
          python setup.py sdist
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: github.event_name == 'release'
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
